//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightPaper.ResourceSatellite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightPaper.ResourceSatellite.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockquote.
        /// </summary>
        public static string _blockquote {
            get {
                return ResourceManager.GetString("_blockquote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string _bold {
            get {
                return ResourceManager.GetString("_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _cancel {
            get {
                return ResourceManager.GetString("_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Options.
        /// </summary>
        public static string _documentOptionsHeader {
            get {
                return ResourceManager.GetString("_documentOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as HTML.
        /// </summary>
        public static string _exportAsHtml {
            get {
                return ResourceManager.GetString("_exportAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Document (*.html)|*.html.
        /// </summary>
        public static string _exportAsHtmlFilter {
            get {
                return ResourceManager.GetString("_exportAsHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string _headers {
            get {
                return ResourceManager.GetString("_headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string _image {
            get {
                return ResourceManager.GetString("_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline Code.
        /// </summary>
        public static string _inlineCode {
            get {
                return ResourceManager.GetString("_inlineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string _italic {
            get {
                return ResourceManager.GetString("_italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string _link {
            get {
                return ResourceManager.GetString("_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string _ok {
            get {
                return ResourceManager.GetString("_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste as Image.
        /// </summary>
        public static string _pasteAsImage {
            get {
                return ResourceManager.GetString("_pasteAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste as Link.
        /// </summary>
        public static string _pasteAsLink {
            get {
                return ResourceManager.GetString("_pasteAsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Options.
        /// </summary>
        public static string _previewOptionsHeader {
            get {
                return ResourceManager.GetString("_previewOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Theme.
        /// </summary>
        public static string _previewThemeOptionLabel {
            get {
                return ResourceManager.GetString("_previewThemeOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Options.
        /// </summary>
        public static string _quickOptions {
            get {
                return ResourceManager.GetString("_quickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string _saveAll {
            get {
                return ResourceManager.GetString("_saveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; has unsaved changes. Do you want to save it?.
        /// </summary>
        public static string _saveConfirmationMessage {
            get {
                return ResourceManager.GetString("_saveConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &apos;{0}&apos;?.
        /// </summary>
        public static string _saveConfirmationTitle {
            get {
                return ResourceManager.GetString("_saveConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Documents (*.md)|*.md|Markdown Documents (*.markdown)|*.markdown|Text Documents (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string _saveDocumentFilter {
            get {
                return ResourceManager.GetString("_saveDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Preview.
        /// </summary>
        public static string _togglePreview {
            get {
                return ResourceManager.GetString("_togglePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Quick Options.
        /// </summary>
        public static string _toggleQuickOptions {
            get {
                return ResourceManager.GetString("_toggleQuickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Sidebar.
        /// </summary>
        public static string _toggleSidebar {
            get {
                return ResourceManager.GetString("_toggleSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string _untitledDocument {
            get {
                return ResourceManager.GetString("_untitledDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words: {0}.
        /// </summary>
        public static string _wordsCount {
            get {
                return ResourceManager.GetString("_wordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Documents.
        /// </summary>
        public static string _workingDocumentsTitle {
            get {
                return ResourceManager.GetString("_workingDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string _yes {
            get {
                return ResourceManager.GetString("_yes", resourceCulture);
            }
        }
    }
}
